### ISSUE TITLE
feat_Appointments

### ISSUE THREAD

**Issue by FrazerAtTAFE** [FrazerAtTAFE/Tafe21S2xx#3]
### Feature
need a form to maintain (add, update & delete) Appointments.

### Due Date
13/09/2021
(Also need time to review and merge to master)

### Note:
Individual student needs to capture the screen shots for the following:
- The Revision Graph that shows the master branch & feature branches
- Use the Show log to display the revision of the master and the feature branches.

**Comment by FrazerAtTAFE** [comment]
Form entry all working and can Read, Update, Delete from the database. Updates ListView too.

Is the ListView meant to show the Time? @vadim-hgg

**Comment by vadim-hgg** [comment]
No, I thought for better readability Appointment name and location should suffice for the list. Do you think it should be full info?

**Comment by FrazerAtTAFE** [comment]
I think it's ok as it is. Ready for Merge!

**Comment by vadim-hgg** [comment]
I still decided to show date and time for the appointment in the list. So implemented the change.
